language: php
php:
  - 7.3
  - 7.4
  - 'nightly'
dist: xenial
env:
  matrix:
    - DB_ENGINE=mysql DB_HOST=localhost DB_USERNAME=root
    - DB_ENGINE=postgres DB_HOST=localhost DB_USERNAME=postgres
services:
  - mysql
  - postgresql
before_install:
  - if [ $DB_ENGINE = 'mysql' ]; then mysql -u root -e 'CREATE DATABASE generate;'; fi
  - if [ $DB_ENGINE = 'postgres' ]; then psql -c 'CREATE DATABASE generate;' -U postgres; fi
before_script:
  - composer install --prefer-source --no-interaction
script:
  - vendor/bin/phpunit --coverage-clover=clover.xml
after_script:
  - wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar
  - php php-coveralls.phar --verbose
cache:
  directories:
    - $HOME/.composer/cache/files